version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # build the application image
     - run: docker build -t $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH .

     # Test uaac in the image works
     - run: docker run -it --rm $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH uaac --version
